"""The Ritz Affair: plot as data. Templates are str.format over V (planted values). ASCII only."""

STOP_WORDS = {"the", "a", "suite", "no", "trunk", "mr", "mrs", "esq", "lord", "senor",
              "senora", "comtesse", "de", "rue", "report", "telegram", "account", "plate",
              "m", "monsieur", "madame", "mme", "miss", "sir", "lady", "countess", "room", "id", "wire", "paris"}

# Season-varying but noise-safe: these full names cannot be produced by generate_db.py's FIRST x LAST pool
# (none of these surnames appear in LAST), so a person.name filter on one is always unambiguous.
COMPETE_FENCE_NAMES = ["Isidore Vasseur", "Anselme Rocher", "Casimir Lenoir", "Ambroise Fontaine", "Theodule Vasseur"]

# Each chapter: n, part, construct, tables revealed when it opens, answer_key (a key of V), solution SQL,
# the naive SQL a student writes without the construct, and naive_rows (its row count, None = any).
CHAPTERS = [
 dict(n=1, board="Police report", part=1, construct="SELECT / WHERE", tables=["police_report", "interview"], answer_key="report_id",
  discovery=[dict(query="SELECT transcript FROM interview WHERE person_name = 'Marcel Duroc'", must_contain="18th of May", note="Duroc says the lift went at 02:10, past midnight: the theft is filed under the 18th, not the 17th.")],
  solution="SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND date = {theft_date} AND type = 'theft'",
  naive="SELECT id FROM police_report WHERE place = 'Hotel Ritz'", naive_rows=None,
  traps=["SELECT id FROM police_report WHERE description LIKE '%Cagliostro%'",
         "SELECT id FROM police_report WHERE description LIKE '%sapphire%'",
         "SELECT id FROM police_report WHERE description LIKE '%Blue Star%'",
         "SELECT id FROM police_report WHERE description LIKE '%balcony%'",
         "SELECT id FROM police_report WHERE description LIKE '%A. L.%'",
         "SELECT id FROM police_report WHERE description LIKE '%porter%'",
         "SELECT id FROM police_report WHERE description LIKE '%lift%'",
         "SELECT id FROM police_report WHERE description LIKE '%Duroc%'",
         "SELECT id FROM police_report WHERE description LIKE '%calling card%'",
         "SELECT id FROM police_report WHERE description LIKE '%pillow%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND description LIKE '%A. L.%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%balcony%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%A. L.%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%lift%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%Duroc%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%pillow%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%calling card%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%sapphire%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%Blue Star%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Ritz' AND type = 'theft' AND description LIKE '%porter%'",
         "SELECT id FROM police_report ORDER BY id DESC LIMIT 1"],
  discovery_compete=[dict(query="SELECT transcript FROM interview WHERE person_name = 'Hippolyte Morand'", must_contain=["11th of June", "a day either side", "no disturbance"])],
  traps_compete=["SELECT id FROM police_report ORDER BY id DESC LIMIT 1",
         "SELECT id FROM police_report WHERE description LIKE '%manager%'",
         "SELECT id FROM police_report WHERE description LIKE '%window%'",
         "SELECT id FROM police_report WHERE description LIKE '%floor%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND type = 'burglary'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND description LIKE '%manager%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND description LIKE '%window%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND type = 'burglary' AND description LIKE '%window%'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date = 19120611 AND type = 'burglary'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date = {compete_night_lo}",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date = {compete_night}",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date = {compete_night_hi}",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date = {compete_quiet_day} AND type = 'burglary'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date BETWEEN {compete_night_lo} AND {compete_night_hi}",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date BETWEEN {compete_night_lo} AND {compete_night_hi} AND type = 'burglary'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND type <> 'disturbance'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date BETWEEN 19120609 AND 19120613 AND type <> 'disturbance'",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date >= {compete_night} AND type = 'burglary' ORDER BY date LIMIT 1",
         "SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date <= {compete_night} AND type = 'burglary' ORDER BY date DESC LIMIT 1"],
  objective_compete="The Meurice night manager knows when, give or take a day.",
  answer_form_compete="the report id",
  solution_compete="SELECT id FROM police_report WHERE place = 'Hotel Meurice' AND date BETWEEN {compete_night_lo} AND {compete_night_hi} AND type <> 'disturbance'",
  naive_compete="SELECT id FROM police_report WHERE place = 'Hotel Meurice'", naive_rows_compete=None,
  answer_key_compete="compete_report_id"),
 dict(n=2, board="The neighbour", board_compete="His suite", part=1, construct="ORDER BY / LIMIT", tables=["hotel_register", "suite"], answer_key="neighbour",
  discovery=[dict(query="SELECT description FROM police_report WHERE id = {report_id}", must_contain="neighbouring suite", note="The report: the thief came from the neighbouring suite, the most expensive one on the floor, the night of the 17th.")],
  solution="SELECT guest_name FROM hotel_register WHERE floor = 2 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price DESC LIMIT 1",
  naive="SELECT guest_name FROM hotel_register WHERE floor = 2 AND checkin <= {eve_date} AND checkout > {eve_date}", naive_rows=7,
  traps=["SELECT guest_name FROM hotel_register WHERE floor = 2 ORDER BY price DESC LIMIT 1"],
  discovery_compete=[dict(query="SELECT description FROM police_report WHERE id = {compete_report_id}", must_contain=["third floor", "two finest"])],
  objective_compete="The report from chapter 1 describes his room. Which suite was it at the Ritz, the night of the 17th of May?",
  answer_form_compete="the suite number",
  solution_compete="SELECT suite FROM hotel_register WHERE floor = 3 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price DESC LIMIT 1 OFFSET 2",
  naive_compete="SELECT suite FROM hotel_register WHERE floor = 3 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price DESC LIMIT 1", naive_rows_compete=1,
  traps_compete=["SELECT suite FROM hotel_register WHERE floor = 3 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price DESC LIMIT 2",
         "SELECT suite FROM hotel_register WHERE floor = 3 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price DESC LIMIT 1 OFFSET 1",
         "SELECT suite FROM hotel_register WHERE floor = 3 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price ASC LIMIT 1",
         "SELECT suite FROM hotel_register WHERE floor = 3 ORDER BY price DESC LIMIT 1 OFFSET 2",
         "SELECT suite FROM hotel_register WHERE floor = 2 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price DESC LIMIT 1 OFFSET 2",
         "SELECT suite FROM hotel_register WHERE floor = 2 AND checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price ASC LIMIT 1",
         "SELECT suite FROM hotel_register WHERE checkin <= {eve_date} AND checkout > {eve_date} ORDER BY price DESC LIMIT 1 OFFSET 2"],
  answer_key_compete="compete_suite2"),
 dict(n=3, board="Licence plate", part=1, construct="LIKE", tables=["cab_ride"], answer_key="plate",
  discovery=[dict(query="SELECT transcript FROM interview WHERE person_name = 'Lord Ashcombe'", must_contain=["{plate_prefix}", "English coins"], note="Ashcombe: the plate began with {plate_prefix}, and the man tipped in English coins."),
             dict(query="SELECT DISTINCT currency FROM cab_ride", must_contain="pound", note="The cab book records the currency of each fare: English coins are 'pound'.")],
  solution="SELECT plate FROM cab_ride WHERE plate LIKE '{plate_prefix}%' AND date = {theft_date} AND currency = 'pound'",
  naive="SELECT plate FROM cab_ride WHERE plate LIKE '{plate_prefix}%' AND date = {theft_date}", naive_rows=None,
  traps=["SELECT plate FROM cab_ride WHERE plate LIKE '{plate_prefix}%' AND currency = 'pound'",
         "SELECT plate FROM cab_ride WHERE plate LIKE '{plate_prefix}%' AND date = {eve_date} AND currency = 'pound'"],
  discovery_compete=[dict(query="SELECT transcript FROM interview WHERE person_name = 'Firmin Lagarde'", must_contain=["{compete_plate_prefix}", "figure before the last was a {lagarde_figure}", "18th of May"])],
  objective_compete="The rival despatcher is sure of two figures of the plate. Find the cab.",
  answer_form_compete="the plate",
  solution_compete="SELECT plate FROM cab_ride WHERE plate LIKE '{compete_plate_pattern}' AND date = {theft_date}",
  naive_compete="SELECT plate FROM cab_ride WHERE plate LIKE '{compete_plate_prefix}%' AND date = {theft_date}", naive_rows_compete=None,
  traps_compete=["SELECT DISTINCT plate FROM cab_ride WHERE dropoff_address_id IS NULL",
         "SELECT plate FROM cab_ride WHERE plate LIKE '{compete_plate_prefix}%' AND dropoff = 'Gare Saint-Lazare' AND date = {theft_date}",
         "SELECT plate FROM cab_ride WHERE plate LIKE '%{lagarde_figure}_' AND date = {theft_date}",
         "SELECT plate FROM cab_ride WHERE plate LIKE '%{lagarde_figure}%' AND date = {theft_date}",
         "SELECT plate FROM cab_ride WHERE plate LIKE '%9%' AND date = {theft_date}",
         "SELECT DISTINCT plate FROM cab_ride WHERE plate LIKE '{compete_plate_pattern}'",
         "SELECT plate FROM cab_ride WHERE plate LIKE '{compete_plate_prefix}%' AND date = {theft_date} AND time < '06:00'",
         "SELECT plate FROM cab_ride WHERE plate LIKE '{compete_plate_prefix}%' AND date = {theft_date} AND currency = 'pound'"],
  answer_key_compete="compete_plate"),
 dict(n=4, board="Fence's address", part=1, construct="GROUP BY / HAVING", tables=[], answer_key="fence_address",
  discovery=[dict(query="SELECT dropoff, COUNT(*) AS n FROM cab_ride WHERE plate = '{plate}' AND date BETWEEN 19120513 AND 19120519 GROUP BY dropoff ORDER BY n DESC", must_contain="{fence_address}", note="The cab's week, 13th to 19th: one address comes back three times.")],
  solution="SELECT dropoff FROM cab_ride WHERE plate = '{plate}' AND date BETWEEN 19120513 AND 19120519 GROUP BY dropoff HAVING COUNT(*) >= 3",
  naive="SELECT DISTINCT dropoff FROM cab_ride WHERE plate = '{plate}' AND date BETWEEN 19120513 AND 19120519", naive_rows=None,
  discovery_compete=[dict(query="SELECT dropoff, COUNT(*) AS fares, COUNT(DISTINCT date) AS days FROM cab_ride WHERE plate = '{compete_plate}' AND date BETWEEN 19120513 AND 19120519 GROUP BY dropoff ORDER BY days DESC, fares DESC", must_contain="{compete_fence_address}")],
  objective_compete="Where did the cab from chapter 3 keep going back to, the week before the theft?",
  answer_form_compete="the address",
  solution_compete="SELECT dropoff FROM cab_ride WHERE plate = '{compete_plate}' AND date BETWEEN 19120513 AND 19120519 GROUP BY dropoff HAVING COUNT(DISTINCT date) >= 3",
  traps_compete=["SELECT dropoff FROM cab_ride WHERE plate = '{compete_plate}' AND date BETWEEN 19120513 AND 19120519 GROUP BY dropoff HAVING COUNT(*) >= 3",
         "SELECT dropoff FROM cab_ride WHERE plate = '{compete_plate}' AND date BETWEEN 19120513 AND 19120519 GROUP BY dropoff HAVING COUNT(DISTINCT date) >= 2",
         "SELECT dropoff FROM cab_ride WHERE plate = '{compete_plate}' GROUP BY dropoff HAVING COUNT(DISTINCT date) >= 3",
         "SELECT dropoff FROM cab_ride WHERE plate = '{compete_plate}' AND date BETWEEN 19120513 AND 19120519 GROUP BY dropoff ORDER BY COUNT(*) DESC LIMIT 1",
         "SELECT dropoff FROM cab_ride WHERE plate = '{compete_plate}' AND date = {theft_date}"],
  naive_compete="SELECT DISTINCT dropoff FROM cab_ride WHERE plate = '{compete_plate}' AND date BETWEEN 19120513 AND 19120519", naive_rows_compete=None,
  answer_key_compete="compete_fence_address"),
 dict(n=5, board="The fence", part=1, construct="JOIN", tables=["person", "address", "guest_card"], answer_key="fence",
  discovery=[
    dict(query="SELECT id FROM address WHERE number = {fence_number} AND street = '{fence_street}'", row_count=1, note="The address's own id."),
    dict(query="SELECT name, occupation FROM person WHERE address_id = (SELECT id FROM address WHERE number = {fence_number} AND street = '{fence_street}')", row_count=5, note="Its five tenants, one of them a jeweller."),
  ],
  solution="SELECT p.name FROM person AS p JOIN address AS a ON p.address_id = a.id WHERE a.number = {fence_number} AND a.street = '{fence_street}' AND p.occupation = 'jeweller'",
  naive="SELECT p.name FROM person AS p JOIN address AS a ON p.address_id = a.id WHERE a.number = {fence_number} AND a.street = '{fence_street}'", naive_rows=5,
  discovery_compete=[
    dict(query="SELECT id FROM address WHERE number = {compete_fence_number} AND street = '{compete_fence_street}'", row_count=1),
    dict(query="SELECT name, occupation FROM person WHERE address_id = (SELECT id FROM address WHERE number = {compete_fence_number} AND street = '{compete_fence_street}')", row_count=5),
    dict(query="SELECT person_id, transcript FROM interview WHERE person_id IN (SELECT id FROM person WHERE address_id = (SELECT id FROM address WHERE number = {compete_fence_number} AND street = '{compete_fence_street}'))", row_count=1),
  ],
  objective_compete="Who is the fence at the address from chapter 4?",
  answer_form_compete="the person's name",
  solution_compete="SELECT p.name FROM person AS p JOIN address AS a ON p.address_id = a.id JOIN interview AS i ON i.person_id = p.id WHERE a.number = {compete_fence_number} AND a.street = '{compete_fence_street}'",
  traps_compete=["SELECT p.name FROM person AS p JOIN address AS a ON p.address_id = a.id WHERE a.number = {compete_fence_number} AND a.street = '{compete_fence_street}' AND p.occupation = 'jeweller'",
         "SELECT p.name FROM person AS p JOIN address AS a ON p.address_id = a.id WHERE a.number = {compete_fence_number} AND a.street = '{compete_fence_street}' AND p.occupation IS NULL",
         "SELECT person_name FROM interview ORDER BY date DESC LIMIT 1"],
  naive_compete="SELECT p.name FROM person AS p JOIN address AS a ON p.address_id = a.id WHERE a.number = {compete_fence_number} AND a.street = '{compete_fence_street}'", naive_rows_compete=5,
  answer_key_compete="compete_fence_name"),
 dict(n=6, board="Shell account", part=1, construct="JOIN x3 + SUM + HAVING", tables=["bank_account", "bank_transaction"], answer_key="shell_account",
  discovery=[
    dict(query="SELECT id FROM bank_account WHERE person_id = (SELECT id FROM person WHERE name = '{fence}')", row_count=1, note="The jeweller's account: {fence_account}."),
    dict(query="SELECT counterparty_id, COUNT(*) AS payments, SUM(amount) AS total, MAX(amount) AS biggest FROM bank_transaction WHERE account_id = {fence_account} AND date BETWEEN 19120501 AND 19120531 GROUP BY counterparty_id ORDER BY total DESC", must_contain="{shell_account}", note="What it paid each account in May. Decoys: the biggest single cheque (one payment), the biggest total (four payments, a supplier), and a second account paid in three small pieces."),
  ],
  solution="SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{fence}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING COUNT(*) = 3 ORDER BY SUM(t.amount) DESC LIMIT 1",
  traps=["SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{fence}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id ORDER BY SUM(t.amount) DESC LIMIT 1",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{fence}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING COUNT(*) >= 3 ORDER BY SUM(t.amount) DESC LIMIT 1",
         "SELECT CAST(substr(text, 12, 5) AS INTEGER) FROM telegram WHERE text LIKE 'PAYMENT TO %'",
         "SELECT id FROM bank_account WHERE person_id IS NULL",
         "SELECT id FROM bank_account ORDER BY id DESC LIMIT 1"],
  naive="SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{fence}' AND t.date BETWEEN 19120501 AND 19120531 ORDER BY t.amount DESC LIMIT 1", naive_rows=1,
  discovery_compete=[
    dict(query="SELECT id FROM bank_account WHERE person_id = (SELECT id FROM person WHERE name = '{compete_fence_name}')", row_count=1),
    dict(query="SELECT counterparty_id, COUNT(*) AS payments, MIN(amount) AS smallest, MAX(amount) AS biggest FROM bank_transaction WHERE account_id = {compete_fence_account} AND date BETWEEN 19120501 AND 19120531 GROUP BY counterparty_id", must_contain="{compete_shell_account}"),
  ],
  objective_compete="Which account did the fence from chapter 5 pay in two equal halves in May?",
  answer_form_compete="the account number",
  solution_compete="SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING COUNT(*) = 2 AND MIN(t.amount) = MAX(t.amount)",
  traps_compete=["SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING COUNT(*) = 2",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING COUNT(*) = 2 ORDER BY SUM(t.amount) DESC LIMIT 1",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING COUNT(*) = 3",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING COUNT(*) = 3 ORDER BY SUM(t.amount) DESC LIMIT 1",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id HAVING MIN(t.amount) = MAX(t.amount)",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' GROUP BY t.counterparty_id HAVING COUNT(*) = 2 AND MIN(t.amount) = MAX(t.amount)",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id ORDER BY SUM(t.amount) DESC LIMIT 1",
         "SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 GROUP BY t.counterparty_id, t.amount HAVING COUNT(*) = 2",
         "SELECT id FROM bank_account WHERE person_id IS NULL AND bank = 'Societe Generale'",
         "SELECT id FROM bank_account ORDER BY id DESC LIMIT 1"],
  naive_compete="SELECT t.counterparty_id FROM person AS p JOIN bank_account AS b ON b.person_id = p.id JOIN bank_transaction AS t ON t.account_id = b.id WHERE p.name = '{compete_fence_name}' AND t.date BETWEEN 19120501 AND 19120531 ORDER BY t.amount DESC LIMIT 1", naive_rows_compete=1,
  answer_key_compete="compete_shell_account"),
 dict(n=7, board="Lupin's wire", board_compete="Broker's wire", part=1, construct="CASE WHEN + GROUP BY", tables=["telegram"], answer_key="night_telegram_id",
  discovery=[dict(query="SELECT CASE WHEN time < '06:00' THEN 'night' WHEN time < '12:00' THEN 'morning' WHEN time < '18:00' THEN 'afternoon' ELSE 'evening' END AS period, COUNT(*) AS wires FROM telegram WHERE office = 'Ritz' AND date = {theft_date} GROUP BY period ORDER BY wires", row_count=4, note="Ganimard's four boxes, counted: the afternoon is the quietest (36), not the night."),
             dict(query="SELECT id, time, sender FROM telegram WHERE office = 'Ritz' AND date = {theft_date} AND time >= '12:00' AND time < '18:00'", row_count=36, note="The quietest box is the afternoon (the races at Longchamp): thirty-six wires. Ortega's suspect card gives the letter, R."),
             dict(query="SELECT id, time, sender FROM telegram WHERE office = 'Ritz' AND date = {theft_date} AND sender = 'R.'", row_count=4, note="Four wires signed R. that day, one per box; three read alike. Only the afternoon one is in the quietest box.")],
  solution="WITH boxed AS (SELECT id, sender, CASE WHEN time < '06:00' THEN 'night' WHEN time < '12:00' THEN 'morning' WHEN time < '18:00' THEN 'afternoon' ELSE 'evening' END AS period FROM telegram WHERE office = 'Ritz' AND date = {theft_date}), quietest AS (SELECT period FROM boxed GROUP BY period ORDER BY COUNT(*) LIMIT 1) SELECT id FROM boxed WHERE sender = 'R.' AND period = (SELECT period FROM quietest)",
  naive="SELECT id FROM telegram WHERE office = 'Ritz' AND date = {theft_date} AND sender = 'R.'", naive_rows=4,
  traps=["SELECT id FROM telegram WHERE office = 'Ritz' AND date = {theft_date} AND time < '06:00' AND sender = 'R.'",
         "SELECT id FROM telegram WHERE office = 'Ritz' AND date = {theft_date} AND sender = 'R.' AND text LIKE 'PAYMENT%'",
         "WITH boxed AS (SELECT id, sender, CASE WHEN time < '06:00' THEN 'night' WHEN time < '12:00' THEN 'morning' WHEN time < '18:00' THEN 'afternoon' ELSE 'evening' END AS period FROM telegram WHERE office = 'Ritz' AND date = {theft_date}), quietest AS (SELECT period FROM boxed GROUP BY period ORDER BY COUNT(*) LIMIT 1) SELECT id FROM boxed WHERE period = (SELECT period FROM quietest)",
         "WITH boxed AS (SELECT id, sender, CASE WHEN time < '06:00' THEN 'night' WHEN time < '12:00' THEN 'morning' WHEN time < '18:00' THEN 'afternoon' ELSE 'evening' END AS period FROM telegram WHERE office = 'Ritz' AND date = {theft_date}), quietest AS (SELECT period FROM boxed GROUP BY period ORDER BY COUNT(*) DESC LIMIT 1) SELECT id FROM boxed WHERE sender = 'R.' AND period = (SELECT period FROM quietest)"],
  discovery_compete=[dict(query="SELECT CASE WHEN time < '10:00' THEN 'before the bell' WHEN time < '15:00' THEN 'the session' WHEN time < '17:00' THEN 'the call' ELSE 'after hours' END AS box, COUNT(*) AS wires FROM telegram WHERE office = 'Bourse' AND date = {theft_date} GROUP BY box ORDER BY wires DESC", row_count=4),
             dict(query="SELECT id, time, text FROM telegram WHERE office = 'Bourse' AND date = {theft_date} AND sender = 'A. Brissac'", row_count=3)],
  objective_compete="Find the broker's wire in the Bourse's busiest box.",
  answer_form_compete="the telegram id",
  solution_compete="WITH boxed AS (SELECT id, sender, CASE WHEN time < '10:00' THEN 'before the bell' WHEN time < '15:00' THEN 'the session' WHEN time < '17:00' THEN 'the call' ELSE 'after hours' END AS box FROM telegram WHERE office = 'Bourse' AND date = {theft_date}), pick AS (SELECT box FROM boxed GROUP BY box ORDER BY COUNT(*) DESC LIMIT 1) SELECT id FROM boxed WHERE sender = 'A. Brissac' AND box = (SELECT box FROM pick)",
  naive_compete="SELECT id FROM telegram WHERE office = 'Bourse' AND date = {theft_date} AND sender = 'A. Brissac'", naive_rows_compete=3,
  traps_compete=["WITH boxed AS (SELECT id, sender, CASE WHEN time < '06:00' THEN 'night' WHEN time < '12:00' THEN 'morning' WHEN time < '18:00' THEN 'afternoon' ELSE 'evening' END AS box FROM telegram WHERE office = 'Bourse' AND date = {theft_date}), pick AS (SELECT box FROM boxed GROUP BY box ORDER BY COUNT(*) DESC LIMIT 1) SELECT id FROM boxed WHERE sender = 'A. Brissac' AND box = (SELECT box FROM pick)",
         "WITH boxed AS (SELECT id, sender, CASE WHEN time < '10:00' THEN 'before the bell' WHEN time < '15:00' THEN 'the session' WHEN time < '17:00' THEN 'the call' ELSE 'after hours' END AS box FROM telegram WHERE office = 'Bourse' AND date = {theft_date}), pick AS (SELECT box FROM boxed GROUP BY box ORDER BY COUNT(*) LIMIT 1) SELECT id FROM boxed WHERE sender = 'A. Brissac' AND box = (SELECT box FROM pick)",
         "WITH boxed AS (SELECT id, sender, CASE WHEN time < '06:00' THEN 'night' WHEN time < '12:00' THEN 'morning' WHEN time < '18:00' THEN 'afternoon' ELSE 'evening' END AS box FROM telegram WHERE office = 'Bourse' AND date = {theft_date}), pick AS (SELECT box FROM boxed GROUP BY box ORDER BY COUNT(*) LIMIT 1) SELECT id FROM boxed WHERE sender = 'A. Brissac' AND box = (SELECT box FROM pick)",
         "SELECT id FROM telegram WHERE sender LIKE '%Brissac%'",
         "SELECT id FROM telegram WHERE office = 'Bourse' AND date = {theft_date} AND text LIKE '%BEFORE DAWN%'",
         "SELECT id FROM telegram WHERE office = 'Bourse' AND date = {theft_date} AND sender = 'A. Brissac' AND time >= '10:00' AND time < '15:00'",
         "SELECT id FROM telegram WHERE office = 'Bourse' AND date = {theft_date} AND sender = 'A. Brissac' ORDER BY time LIMIT 1",
         "SELECT id FROM telegram WHERE office = 'Bourse' AND date = {theft_date} AND sender = 'A. Brissac' ORDER BY time DESC LIMIT 1"],
  answer_key_compete="compete_telegram_id"),
 dict(n=8, board="Lupin's alias", board_compete="Broker's suite", explain="Rank each suite's orders of the 18th by time: his is the suite whose FIRST order is the champagne, before six (Ortega also drank it that night, but after a coffee). The register names that suite's guest.",
  part=1, construct="RANK() OVER + CTE", tables=["room_service"], answer_key="lupin_alias",
  discovery=[dict(query="SELECT text FROM telegram WHERE id = {night_telegram_id}", must_contain="{champagne}", note="The night wire names his first order before dawn: {champagne}.")],
  solution="WITH ranked AS (SELECT suite, item, time, RANK() OVER (PARTITION BY suite ORDER BY time) AS rk FROM room_service WHERE date = {theft_date}), his_suite AS (SELECT suite FROM ranked WHERE rk = 1 AND item = '{champagne}' AND time < '06:00') SELECT guest_name FROM hotel_register WHERE floor = 2 AND checkin <= {theft_date} AND checkout > {theft_date} AND suite = (SELECT suite FROM his_suite)",
  naive="SELECT DISTINCT suite FROM room_service WHERE date = {theft_date} AND item = '{champagne}' AND time < '06:00'", naive_rows=2,
  traps=["SELECT guest_name FROM hotel_register WHERE floor = 2 AND checkin <= {theft_date} AND checkout > {theft_date} AND suite = (SELECT suite FROM telegram WHERE id = {night_telegram_id})",
         "SELECT guest_name FROM hotel_register WHERE floor = 2 AND checkin <= {theft_date} AND checkout > {theft_date} AND suite = (SELECT suite FROM room_service WHERE date = {theft_date} AND item = '{champagne}' ORDER BY time LIMIT 1)"],
  discovery_compete=[dict(query="SELECT text FROM telegram WHERE id = {compete_telegram_id}", must_contain="cognac")],
  telegram_compete="MY DEAR GANIMARD STOP GARE DU NORD NINE FIFTEEN STOP DO NOT BE LATE STOP THE BLUE STAR SENDS REGARDS FROM LONDON STOP A L",
  objective_compete="The wire from chapter 7 names his habit. Which suite had it as its last order before dawn on the 18th?",
  answer_form_compete="the suite number",
  solution_compete="WITH ranked AS (SELECT suite, item, time, RANK() OVER (PARTITION BY suite ORDER BY time DESC) AS rk FROM room_service WHERE date = {theft_date} AND time < '06:00') SELECT suite FROM ranked WHERE rk = 1 AND item = 'cognac'",
  naive_compete="SELECT DISTINCT suite FROM room_service WHERE date = {theft_date} AND item = 'cognac' AND time < '06:00'", naive_rows_compete=3,
  traps_compete=["WITH ranked AS (SELECT suite, item, time, RANK() OVER (PARTITION BY suite ORDER BY time) AS rk FROM room_service WHERE date = {theft_date}) SELECT suite FROM ranked WHERE rk = 2 AND item = 'coffee' AND time < '06:00'",
         "WITH ranked AS (SELECT suite, item, time, RANK() OVER (PARTITION BY suite ORDER BY time) AS rk FROM room_service WHERE date = {theft_date}) SELECT suite FROM ranked WHERE rk = 2 AND item = 'cognac' AND time < '06:00'",
         "WITH ranked AS (SELECT suite, item, time, RANK() OVER (PARTITION BY suite ORDER BY time) AS rk FROM room_service WHERE date = {theft_date} AND time < '06:00') SELECT suite FROM ranked WHERE rk = 1 AND item = 'cognac'",
         "WITH ranked AS (SELECT suite, item, time, RANK() OVER (PARTITION BY suite ORDER BY time DESC) AS rk FROM room_service WHERE date = {theft_date}) SELECT suite FROM ranked WHERE rk = 1 AND item = 'cognac' AND time < '06:00'",
         "WITH ranked AS (SELECT suite, item, time, RANK() OVER (PARTITION BY suite ORDER BY time DESC) AS rk FROM room_service WHERE date = {theft_date}) SELECT suite FROM ranked WHERE rk = 1 AND item = 'cognac'",
         "SELECT suite FROM room_service WHERE date = {theft_date} AND item = 'cognac' AND time < '06:00' ORDER BY time DESC LIMIT 1",
         "SELECT suite FROM room_service WHERE date = {theft_date} AND item = 'cognac' AND time < '06:00' ORDER BY time LIMIT 1",
         "SELECT suite FROM room_service WHERE date = {theft_date} AND item = 'cognac' ORDER BY time DESC LIMIT 1"],
  answer_key_compete="compete_suite8"),
 dict(n=9, board="The trunk", explain="Put each of Ashcombe's trunks next to the ticket it travelled on and the name of the ticket's holder, then keep the one whose holder is neither His Lordship nor his valet nor his maid: the unknown gentleman who paid cash.",
  part=2, construct="CTE + JOIN", tables=["train_ticket", "luggage"], answer_key="trunk_no",
  solution="WITH ashcombe_trunks AS (SELECT l.trunk_no, t.person_id FROM luggage AS l JOIN train_ticket AS t ON l.ticket_id = t.id WHERE l.owner_name = '{neighbour}') SELECT trunk_no FROM ashcombe_trunks AS a JOIN person AS p ON a.person_id = p.id WHERE p.name NOT IN ('{neighbour}', 'Bertram Hobbs', 'Ada Pringle')",
  naive="SELECT trunk_no FROM luggage WHERE owner_name = '{neighbour}'", naive_rows=8,
  traps=["SELECT MIN(trunk_no) FROM luggage WHERE owner_name = '{neighbour}' GROUP BY ticket_id HAVING COUNT(*) = 1",
         "SELECT l.trunk_no FROM luggage AS l JOIN train_ticket AS t ON l.ticket_id = t.id WHERE l.owner_name = '{neighbour}' AND t.person_id IN (SELECT t2.person_id FROM luggage AS l2 JOIN train_ticket AS t2 ON l2.ticket_id = t2.id WHERE l2.owner_name = '{neighbour}' GROUP BY t2.person_id HAVING COUNT(*) = 1)",
         "SELECT l.trunk_no FROM luggage AS l JOIN train_ticket AS t ON l.ticket_id = t.id JOIN person AS p ON t.person_id = p.id WHERE l.owner_name = '{neighbour}' AND p.name <> '{neighbour}'",
         "SELECT l.trunk_no FROM luggage AS l JOIN train_ticket AS t ON l.ticket_id = t.id JOIN person AS p ON t.person_id = p.id WHERE p.address_id IS NULL"]),
 dict(n=10, board="Second alias", explain="Regulars have six stays or more. Two stays share a night when each checks in before the other checks out; keep the regular who never shares one with Blakeney. Almagro and Sernine share a night with him (11 January, and the week of the theft), so one name is left: the same man, under two names.",
  part=2, construct="Self-join", tables=[], answer_key="double_alias",
  solution="WITH regulars AS (SELECT guest_name FROM hotel_register GROUP BY guest_name HAVING COUNT(*) >= 6), blakeney AS (SELECT checkin, checkout FROM hotel_register WHERE guest_name = '{lupin_alias}'), shared AS (SELECT DISTINCT y.guest_name FROM hotel_register AS y JOIN blakeney AS x ON x.checkin < y.checkout AND y.checkin < x.checkout) SELECT r.guest_name FROM regulars AS r LEFT JOIN shared AS s ON s.guest_name = r.guest_name WHERE s.guest_name IS NULL",
  naive="SELECT guest_name FROM hotel_register GROUP BY guest_name HAVING COUNT(*) >= 6", naive_rows=None,
  traps=["SELECT DISTINCT guest_name FROM hotel_register WHERE suite = {lupin_suite} AND checkin < 19120501 AND guest_name <> '{lupin_alias}'",
         "SELECT DISTINCT guest_name FROM hotel_register WHERE price = 150 AND guest_name <> '{lupin_alias}'",
         "SELECT guest_name FROM hotel_register WHERE guest_name <> '{lupin_alias}' GROUP BY guest_name ORDER BY SUM(checkout - checkin = 6) DESC LIMIT 1",
         "SELECT name FROM person WHERE occupation = 'gentleman' AND name <> '{lupin_alias}'"]),
 dict(n=11, board="Silent suite", explain="Merge the night's three ledgers into one list of (suite, time); LAG gives each event the suite's previous one. The silent suite has an event at or before 02:05 followed by nothing until 03:10 or later. Velmont's suite is silent longer, 02:30 to 05:55, but only after the lift the porter heard.",
  part=2, construct="LAG() OVER", tables=["lift_log"], answer_key="lupin_suite",
  solution="WITH ev AS (SELECT suite, time FROM lift_log WHERE date = {theft_date} AND time < '06:00' UNION ALL SELECT suite, time FROM room_service WHERE date = {theft_date} AND time < '06:00' UNION ALL SELECT suite, time FROM telegram WHERE date = {theft_date} AND time < '06:00' AND suite IS NOT NULL), gaps AS (SELECT suite, time, LAG(time) OVER (PARTITION BY suite ORDER BY time) AS prev FROM ev) SELECT suite FROM gaps WHERE prev <= '02:05' AND time >= '03:10'",
  naive="SELECT suite FROM lift_log WHERE date = {theft_date} AND time < '06:00' GROUP BY suite HAVING COUNT(*) <= 2", naive_rows=2,
  traps=["SELECT suite FROM lift_log WHERE date = {theft_date} AND time BETWEEN '02:00' AND '02:20'",
         "WITH ev AS (SELECT suite, time FROM lift_log WHERE date = {theft_date} AND time < '06:00' UNION ALL SELECT suite, time FROM room_service WHERE date = {theft_date} AND time < '06:00' UNION ALL SELECT suite, time FROM telegram WHERE date = {theft_date} AND time < '06:00' AND suite IS NOT NULL), gaps AS (SELECT suite, time, LAG(time) OVER (PARTITION BY suite ORDER BY time) AS prev FROM ev) SELECT suite FROM gaps WHERE prev <= '02:10' AND time >= '02:10' AND (CAST(substr(time, 1, 2) AS INTEGER) * 60 + CAST(substr(time, 4, 2) AS INTEGER)) - (CAST(substr(prev, 1, 2) AS INTEGER) * 60 + CAST(substr(prev, 4, 2) AS INTEGER)) = 60"],
  discovery=[dict(query="SELECT time, suite, direction FROM lift_log WHERE date = {theft_date} AND time < '06:00' ORDER BY time", must_contain=["02:05", "03:10"], note="The lift that night: one suite rang at 02:05 (down) and 03:10 (up), and nothing in between.")]),
 dict(n=12, board="Where the money went", explain="Add up each account's transfers to each counterparty after the theft (one hop was paid in two halves). From the shell account's {chain_amount} francs, follow only the transfer worth 98 percent of the previous one, to the franc (a shell account's other deal that day falls away), seven hops down, then read the owner.",
  part=2, construct="WITH RECURSIVE", tables=[], answer_key="comtesse",
  solution="WITH RECURSIVE flows AS (SELECT account_id, counterparty_id, SUM(amount) AS amount FROM bank_transaction WHERE date >= {theft_date} AND type = 'transfer' GROUP BY account_id, counterparty_id), chain(account_id, amount, hop) AS (SELECT {shell_account}, {chain_amount}, 0 UNION ALL SELECT f.counterparty_id, f.amount, c.hop + 1 FROM chain AS c JOIN flows AS f ON f.account_id = c.account_id WHERE ABS(f.amount - c.amount * 0.98) <= 1) SELECT p.name FROM chain AS c JOIN bank_account AS b ON b.id = c.account_id JOIN person AS p ON p.id = b.person_id WHERE c.hop = 7",
  naive="WITH RECURSIVE chain(account_id, amount, hop) AS (SELECT {shell_account}, {chain_amount}, 0 UNION ALL SELECT t.counterparty_id, t.amount, c.hop + 1 FROM chain AS c JOIN bank_transaction AS t ON t.account_id = c.account_id WHERE ABS(t.amount - c.amount * 0.98) <= 1) SELECT account_id FROM chain WHERE hop = 7", naive_rows=0,
  traps=["SELECT p.name FROM bank_transaction AS t JOIN bank_account AS b ON b.id = t.counterparty_id JOIN person AS p ON p.id = b.person_id WHERE t.amount > 20000 AND t.date >= {theft_date} ORDER BY t.date DESC LIMIT 1",
         "SELECT p.name FROM bank_account AS b JOIN person AS p ON p.id = b.person_id WHERE b.id >= 60000",
         "SELECT p.name FROM bank_account AS b JOIN person AS p ON p.id = b.person_id ORDER BY b.id DESC LIMIT 1"]),
]

# The Suspects gallery. A suspect appears once met: when the story of an unlocked chapter names them (`meet`),
# or earlier if a query result the student sees shows their name. Each note is added to the bio once chapter n
# is unlocked (reached), so it may tell what the chapter before it revealed, never the one being played.
CAST = [
    dict(name="Lord Ashcombe", nationality="English", meet=3,
         bio="Peer of the realm. Collects clocks and grievances.",
         notes=[[3, "Was at the Opera until one. His valet saw a man in an English coat leave by the service door."],
                [9, "Left for London on the boat train of the 19th, with his trunks."],
                [10, "Carried the Blue Star through customs with a clear conscience, in a trunk he never packed."]]),
    dict(name="Paul Sernine", nationality="French", meet=10,
         bio="Rentier. Nobody has ever seen him pay for anything.",
         notes=[[10, "A regular at the Ritz since January."],
                [11, "Slept at the Ritz on the night of 11 January, when Mr. Blakeney did."]]),
    dict(name="Horace Velmont", nationality="French", meet=11,
         bio="Painter of society portraits. Paints mostly at night.",
         notes=[[11, "Seldom in his suite after dark."],
                [12, "Out from 02:30 to 05:55 on the night of the theft, painting the Prefect's wife. The Prefect confirms it, twice."]]),
    dict(name="Raul Ortega", nationality="Argentine", meet=7,
         bio="Cattle baron. Signs everything with a flourish and an R.",
         notes=[[7, "Complains that the Ritz desk keeps mixing up his wires with another guest's, who also signs R."],
                [8, "Wired Buenos Aires from the Ritz desk at 06:20 on the 18th: morning, by Ganimard's clock."],
                [9, "Drinks champagne before dawn, but only after his coffee."]]),
    dict(name="Ines de Almagro", nationality="Spanish", meet=10,
         bio="Widow. Never travels without her maid.",
         notes=[[10, "A regular at the Ritz since January, never without her maid."],
                [11, "Slept at the Ritz on the night of 11 January, when Mr. Blakeney did."]]),
    dict(name="Rupert Blakeney", nationality="English", meet=9,
         bio="Gentleman of leisure from Bath.",
         notes=[[9, "His first order before dawn on the 18th: champagne, as always."],
                [10, "Wears an excellent coat, the kind a booking clerk remembers."],
                [11, "At the Ritz every other week since January, never on the same nights as Mr. Grey."],
                [12, "His suite was silent from 02:05 to 03:10 on the night of the theft."]]),
]

# keys are normalised names (see generate_db.normalise), so the page can look a wrong answer up directly
WRONG_SUSPECTS = {
  "paul sernine": "An anagram, Ganimard? Lupin is vain, not stupid. Sernine is released with apologies.",
  "horace velmont": "Velmont was painting the Prefect's wife at the hour of the theft. The Prefect confirms it, twice.",
  "raul ortega": "Senor Ortega produces a receipt for the champagne and a lawyer for everything else.",
  "ines almagro": "The Senora faints. The maid does not. Neither is Lupin.",
  "ashcombe": "You arrest the peer in the neighbouring suite. He is the Prefect's cousin. Awkward.",
  "arsene lupin": "Yes. Under which name? That is rather the question.",
  "grey": "Mr. Grey checked out this morning. The concierge is certain, because Mr. Grey tipped him.",
  "ganimard": "The inspector reads your note, takes off his hat, and puts it back on. 'Out.'",
}
WRONG_DEFAULT = [
  "Ganimard reads your note twice and lights his pipe. 'No.'",
  "The clerk before you was dismissed for less. Try again.",
  "Not that, mon petit. Look at the data again.",
]
ENDINGS = dict(
  part1="Gare du Nord, 20 May, 09:10. **Ganimard** is early: *Lupin had asked him not to be late.* His hand falls on the shoulder of **{lupin_alias}, Esq.**\n\n*'Monsieur {lupin_alias}. You are under arrest.'*\n\nThe gentleman smiles. *'Delighted, Inspector.'* He lets the inspector take the small velvet case from his hand. Ganimard opens it. *It is empty.*\n\nA gendarme leads the prisoner away in handcuffs, still smiling. Behind them, the boat train pulls out, a day behind the Blue Star: *it crossed yesterday, in a trunk.*",
  part2="The **Comtesse** receives **Ganimard** in her suite, now insured for three hundred thousand francs. She offers tea. Ganimard declines, *which is a first*, and lays the bank's ledger on her desk: sold for forty thousand, insured for three hundred.\n\n*'Arithmetic, Inspector.'*\n\n*'Madame la Comtesse, you are under arrest.'* The jeweller bought nothing: the forty thousand were hers, sent round seven doors to come home as a sale. She asks for her furs. You are promoted to a desk with a window. **Lupin**, in London, sends a telegram.",
)

TEXT = {
 1: dict(
  title="The Night of the 17th",
  story="*Four in the morning, the Prefecture.* **Ganimard** comes back from the Ritz with his collar undone and his temper worse. He drops a stack of police reports on your desk: *every theft, fraud and lost umbrella in Paris this spring.*\n\n*'**One of these is ours**, clerk. **Marcel Duroc**, the night porter, was in the lobby all night. He never sleeps and never forgets.'*",
  story_compete="*Four in the morning, the Prefecture.* **Ganimard** has not slept since the Ritz, and now the *Hotel Meurice* has been burgled as well. He drops a stack of police reports on your desk: *every theft, fraud and lost umbrella in Paris this spring.*\n\n*'**One of these is the Meurice**, clerk. **Hippolyte Morand**, the night manager, found the damage himself. His clocks and ours have never agreed, so he will not swear to the night, only to near it. And mind what he says it was not.'*",
  objective="Mr Duroc knows which night.",
  answer_form="the report id",
  telegram="MY DEAR GANIMARD STOP YOU FOUND THE REPORT STOP THE BALCONY WAS DELIGHTFUL STOP I LEFT MY CARD ON THE PILLOW STOP A L"),
 2: dict(
  title="The Neighbouring Suite",
  story="**Ganimard** drops the report you found back on your desk. *'It is all in here, clerk, if you read it properly. I am not paid to read twice.'*\n\nThe Ritz has sent over its *register*: every guest, every suite and every price since January.",
  story_compete="**Ganimard** reads the Meurice report you found and swears, once. *'Our man practises, clerk. What he did at the Meurice in June, he had done at the Ritz in May: the same floor, the same taste in rooms.'*\n\nThe Ritz has sent over its *register*: every guest, every suite and every price since January. *'Two suites at the top of that floor share one price: the royal pair. He never touches those. Find me **the one just below the royal pair**, the night of the 17th of May.'*",
  objective="The report says where the thief came from. Who slept there?",
  answer_form="the guest's name",
  telegram="MY DEAR GANIMARD STOP HIS LORDSHIP SNORES STOP I CROSSED HIS BALCONY TWICE AND HE NEVER STIRRED STOP HIS VALET SLEEPS LESS STOP ASK HIM ABOUT MY COAT STOP A L"),
 3: dict(
  title="A Plate in the Dark",
  story="**His Lordship**, woken at dawn, is displeased but useful. *'My valet saw the man,'* he says, *'and his account is with your inspector already. Read it, if you doubt a peer's memory.'*\n\nThe cab company keeps a book of every fare. **Ganimard** wants **the cab that took our man**.",
  story_compete="Whoever slept in that room did not walk home. **Ganimard** has found a second cab book: a rival company, which writes down its fares as carefully as the first and trusts its drivers less.\n\nIts despatcher, **Firmin Lagarde**, has already talked to the inspector. *'He is sure of two figures, clerk, and of nothing in between. Read what he said, then find me **the cab that took our second man**.'*",
  objective="Read what the neighbour told Ganimard, then find the cab.",
  answer_form="the plate",
  telegram="MY DEAR GANIMARD STOP THE CAB SMELLED OF CIGARS STOP THE DRIVER KNOWS THE WAY STOP HE HAS TAKEN ME THERE BEFORE STOP READ HIS WEEK STOP A L"),
 4: dict(
  title="The Cab's Week",
  story="**Ganimard** snorts at the plate. *'A gentleman thief does not hail cabs, clerk. He keeps one, with a driver paid to forget where he goes. But the company pays the same driver to write it all down.'*\n\nThe book holds some sixty fares for that cab in the week before the theft, from the 13th to the 19th of May. *'A thief with a plan visits his fence before the job. Find me **the address this cab kept going back to**. I do not want the list. I want the address.'*",
  story_compete="**Ganimard** taps the plate you found in chapter 3. *'A second cab, clerk, and a second driver paid to forget. But his company pays him to write it all down.'*\n\nThe book holds that cab's fares for the week before the theft, from the 13th to the 19th of May. *'A wedding brings a cab back to one door again and again in a single afternoon. A fence brings it back day after day. Find me **the address it went back to on three different days**.'*",
  objective="Where did the cab from chapter 3 keep going the week before the theft?",
  answer_form="the address",
  telegram="MY DEAR GANIMARD STOP THREE TIMES TO THE SAME DOOR STOP HABIT IS THE ENEMY OF ART STOP THE HOUSE HAS FIVE TENANTS AND ONE OF THEM OWNS A LOUPE STOP A L"),
 5: dict(
  title="The Boarding House",
  story="The address is a boarding house: five tenants, and a landlady who has *seen nothing since 1889*.\n\n**Ganimard** wants the jeweller among them. Every fence in Paris calls himself a jeweller.",
  story_compete="The address is another boarding house: five tenants, and a concierge who has *minded her own business since the Commune*.\n\nOne of the tenants is a jeweller, and **Ganimard** could not care less. *'Every fence in Paris calls himself a jeweller, clerk, so ours calls himself nothing at all. He came to the police before we came to him: find me **the tenant who gave us a statement**.'*",
  objective="Who is the jeweller at the address from chapter 4?",
  answer_form="the person's name",
  telegram="MY DEAR GANIMARD STOP GRIMAUD PAID ME WELL AND PROMPTLY STOP HE BANKS AT THE CREDIT LYONNAIS STOP HE PAYS A GREAT MANY PEOPLE STOP A L"),
 6: dict(
  title="Follow the Francs",
  story="The jeweller banks at the *Credit Lyonnais*, and **Ganimard** has a warrant, so the bank hides nothing. Its ledger has one line per transfer: the account that paid, the account that was paid, the sum and the day.\n\n*'A fence pays a thief in three pieces, clerk: one for the job, one for the silence, one for the road. The bank does not blink at small sums. And of all the men he paid that way in May, **ours was paid best**.'*",
  story_compete="The fence banks at the *Societe Generale*, and **Ganimard**'s warrant opens that ledger too: one line per transfer, the account that paid, the account that was paid, the sum and the day.\n\n*'This one is tidier than the last, clerk. No three pieces for him: he paid his man in **two equal halves** in May, the same to the franc. Not two odd sums, and not three.'*",
  objective="Of the accounts the jeweller from chapter 5 paid in three pieces in May, which received the most?",
  answer_form="the account number",
  telegram="MY DEAR GANIMARD STOP THREE PIECES AND THE BEST SHARE STOP YOU ARE LEARNING STOP I CONFIRMED RECEIPT BY WIRE FROM THE RITZ DESK AT ITS QUIETEST STOP THE CLERK THERE READS NOTHING STOP A L"),
 7: dict(
  title="The Quietest Hour",
  story="Lupin wrote that he confirmed the payment by wire from the Ritz desk, at its quietest. The desk sent a hundred and seventy-odd wires on the 18th, and its clerk is *too proud to have read any of them*.\n\n**Ganimard** does not count hours the way you do. His day has four boxes:\n\n| Box | From | Before |\n| Night | 00:00 | 06:00 |\n| Morning | 06:00 | 12:00 |\n| Afternoon | 12:00 | 18:00 |\n| Evening | 18:00 | midnight |\n\n*'The quietest box is the one with the fewest wires, clerk. His wire is in it. He signs with one letter, which is one more than he needs. Which letter? Ask **Senor Ortega**: his card is in the Suspects file, and he has been complaining about it at the desk all week.'*",
  story_compete="The money was confirmed by wire, through a broker at the *Bourse*. **Anatole Brissac** signs every wire he sends, and the Bourse telegraph office sent dozens on the 18th.\n\nThe Bourse keeps its own hours, and **Ganimard** boxes its day its own way:\n\n| Box | From | Before |\n| Before the bell | 00:00 | 10:00 |\n| The session | 10:00 | 15:00 |\n| The call | 15:00 | 17:00 |\n| After hours | 17:00 | midnight |\n\n*'A broker hides in a crowd, clerk. He wired in three of those boxes that day, and his real wire went out in **the busiest box**, the one with the most wires.'*",
  objective="Find the wire he signed at the Ritz desk on the 18th, in the quietest of Ganimard's four boxes.",
  answer_form="the telegram id",
  telegram="MY DEAR GANIMARD STOP YOU READ MY WIRE STOP AS ALWAYS MY FIRST ORDER BEFORE DAWN STOP A MAN OF HABIT IS A MAN WITH A ROOM NUMBER STOP A L"),
 8: dict(
  title="The First Order Before Dawn",
  story="**Ganimard** reads aloud the wire you found in chapter 7: *'as always my first order before dawn'*. It names the drink, too.\n\n*'A man of habit is a man with a room number, clerk. And before dawn, at my age, means before six.'*",
  story_compete="**Ganimard** reads aloud the broker's wire you found in chapter 7. It names his habit before dawn, *as always*.\n\n*'A broker who sells for a fence sleeps close to his client, clerk. That night he slept at the Ritz, and room service writes down every order, in order. I want the suite where it was **his last order before dawn**. And before dawn, at my age, means before six.'*",
  objective="The wire from chapter 7 describes a habit. Whose was it, on the 18th?",
  answer_form="the guest's name",
  telegram="MY DEAR GANIMARD STOP GARE DU NORD NINE FIFTEEN STOP DO NOT BE LATE STOP THE BLUE STAR SENDS REGARDS FROM LONDON STOP CHAPTER IX IF YOU DARE STOP A L"),
 9: dict(
  title="The Trunk",
  story="**Ganimard** has gone home to his cat: his prisoner walked out of the *Depot* on the 21st, and the gendarme who led him away has not been found. *You have not gone home.*\n\nThe Blue Star *'sends regards from London'*. The boat train left the Gare du Nord on the 19th, and the peer from chapter 2 was on it with his valet, **Bertram Hobbs**, his maid, **Ada Pringle**, and his trunks. Each of the three held a ticket. The *Compagnie du Nord* enters every trunk under an owner's name and a ticket number, and nobody checks that the two agree.",
  objective="Find the trunk labelled for the neighbour that travelled on the ticket of someone outside his household.",
  answer_form="the trunk number",
  telegram="MY DEAR CLERK STOP HIS LORDSHIP CARRIED THE STONE THROUGH CUSTOMS WITH A CLEAR CONSCIENCE STOP THE TICKET WAS BOUGHT BY A REGULAR STOP YOU HAVE NEVER SEEN US TOGETHER STOP A L"),
 10: dict(
  title="Never Seen Together",
  story="The ticket held by nobody of His Lordship's household was bought for cash. The booking clerk remembers only *'a regular, monsieur, English, excellent coat'*, which describes half the Ritz's second floor.\n\nThe regulars include the **Senora de Almagro**, **M. Sernine** and the gentleman from chapter 8. You have *a suspicion of the theatrical kind*: **two names, one man**. And one man cannot sleep in two suites on the same night.",
  objective="Find the regular (six stays or more) who has never slept at the Ritz on the same night as the gentleman from chapter 8.",
  answer_form="the guest's name",
  telegram="MY DEAR CLERK STOP BLAKENEY IN THE ODD WEEKS GREY IN THE EVEN STOP THE CONCIERGE NEVER NOTICED STOP ON THE NIGHT OF THE 17TH MY SUITE WAS VERY QUIET FOR ONE HOUR STOP A L"),
 11: dict(
  title="The Silence",
  story="**Ganimard** wants to know **who was out of his suite when the sapphire went**. A Ritz suite is never quite silent at night: the lift boy notes every ring, room service every order, and the telegraph desk every wire charged to a suite.\n\nLaid side by side, the three ledgers show one suite on the second floor going quiet for an hour, around the time the porter heard the lift at 02:10. It is not the only quiet suite. **M. Velmont** paints at night, in his studio, and often comes back to the Ritz only at dawn.",
  objective="Which suite fell silent on the night of the theft?",
  answer_form="the suite number",
  telegram="MY DEAR CLERK STOP ONE HOUR AND FIVE MINUTES STOP THE BALCONY THE STONE THE CAB THE JEWELLER AND BACK FOR CHAMPAGNE STOP AND THE FORTY THOUSAND FRANCS STOP WHERE DO YOU THINK THEY WENT STOP A L"),
 12: dict(
  title="Follow the Money",
  story="The forty thousand francs did not stay in the shell account of chapter 6. They moved on, through shell accounts at four banks, into June. What **Ganimard** knows:\n\n| The road | |\n| Starts | at the shell account of chapter 6, forty thousand francs |\n| First move | the 20th of May, then every three days or so |\n| At every door | two percent stays behind: the next account gets ninety-eight |\n| One door | was paid in two halves, the same day |\n| Doors | seven |\n\nFollow the ninety-eight percent, and only the ninety-eight percent, and **read the name on the last account**. Ganimard will not like it.",
  objective="Follow the ninety-eight percent from the account of chapter 6, seven doors down. Whose is the last account?",
  answer_form="the person's name",
  telegram="MY DEAR GANIMARD STOP INSURANCE PAYS THREE HUNDRED THOUSAND FOR A STONE WORTH FORTY THOUSAND STOP ARITHMETIC IS THE GREATEST OF CRIMES STOP A L"),
}
for _ch in CHAPTERS:
    _ch.update(TEXT[_ch["n"]])
